<a href="https://colab.research.google.com/github/khustule/pyAssignment/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy


In [ ]:
import numpy as np

In [ ]:
a = np.array([[45,5,5,5,4,5,5,5],[1,10,5,50,4,5,5,5],[5,74,4,56,5,3,3,3],[55,4,4,8,5,1,1,1],[4,5,66,22,4,1,1,1]])
print(a,"\n", a.shape, "\n" ,a.ndim, "\n", a.dtype)

[[45  5  5  5  4  5  5  5]
 [ 1 10  5 50  4  5  5  5]
 [ 5 74  4 56  5  3  3  3]
 [55  4  4  8  5  1  1  1]
 [ 4  5 66 22  4  1  1  1]] 
 (5, 8) 
 2 
 int64


In [ ]:
a = np.array([[45,55,5,4],[1,10,5,50],[5,74,4,56],[55,4,4,8]])
print(a,"\n", a.shape, "\n" ,a.ndim, "\n", a.dtype)

[[45 55  5  4]
 [ 1 10  5 50]
 [ 5 74  4 56]
 [55  4  4  8]] 
 (4, 4) 
 2 
 int64


In [ ]:
a = np.array([[1,5,6]])
print(a)
print(a.shape)
print(a.ndim)

[[1 5 6]]
(1, 3)
2


In [ ]:
a = np.array([[45,55],[1,5],[5,7]])
print(a,"\n", a.shape, "\n" ,a.ndim, "\n", a.dtype)

[[45 55]
 [ 1  5]
 [ 5  7]] 
 (3, 2) 
 2 
 int64


In [ ]:
a = np.array([[[45,55,1],[5,4,5]],[[1,10,5],[5,5,10]],[[5,7,4],[4,5,6]],[[5,5,4],[4,8,4]]])
print(a,"\n", a.shape, "\n" ,a.ndim, "\n", a.dtype)

[[[45 55  1]
  [ 5  4  5]]

 [[ 1 10  5]
  [ 5  5 10]]

 [[ 5  7  4]
  [ 4  5  6]]

 [[ 5  5  4]
  [ 4  8  4]]] 
 (4, 2, 3) 
 3 
 int64


In [ ]:
a = np.array([[[45,5,5,1],[5,4,5,1],[5,4,5,4]],[[1,10,5,5],[5,5,10,6],[5,4,5,6]],[[5,7,4,5],[4,5,6,4],[5,4,5,5]]])
print(a,"\n", a.shape, "\n" ,a.ndim, "\n", a.dtype)

[[[45  5  5  1]
  [ 5  4  5  1]
  [ 5  4  5  4]]

 [[ 1 10  5  5]
  [ 5  5 10  6]
  [ 5  4  5  6]]

 [[ 5  7  4  5]
  [ 4  5  6  4]
  [ 5  4  5  5]]] 
 (3, 3, 4) 
 3 
 int64


In [ ]:
a = np.array([[45,55],[1,5],[5,7],[45,55],[45,55],[45,55],[45,55],[45,55],[45,55],[45,55],[45,55],[45,55]])
print(a,"\n", a.shape, "\n" ,a.ndim, "\n", a.dtype)                          

[[45 55]
 [ 1  5]
 [ 5  7]
 [45 55]
 [45 55]
 [45 55]
 [45 55]
 [45 55]
 [45 55]
 [45 55]
 [45 55]
 [45 55]] 
 (12, 2) 
 2 
 int64


In [ ]:
a = np.array([[[[1,2]],[[4,6]]]])
print(a,"\n", a.shape, "\n" ,a.ndim, "\n", a.dtype) 

[[[[1 2]]

  [[4 6]]]] 
 (1, 2, 1, 2) 
 4 
 int64


In [ ]:
a = np.array([[[[1,2]]],[[[1,2]]]])
print(a,"\n", a.shape, "\n" ,a.ndim, "\n", a.dtype)

[[[[1 2]]]


 [[[1 2]]]] 
 (2, 1, 1, 2) 
 4 
 int64


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a=np.ones((3,8,9))
print(a)

[[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]]]


In [ ]:
a=np.full((3,8,9),6)
print(a)

[[[6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]]

 [[6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]]

 [[6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6 6]]]


In [ ]:
a=np.eye((3))
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
np.random.random((4,5,2))

array([[[0.33123533, 0.54643669],
        [0.19011088, 0.35186093],
        [0.23131556, 0.04032917],
        [0.52306842, 0.15098552],
        [0.45627856, 0.74467696]],

       [[0.20855776, 0.36330282],
        [0.0025327 , 0.20249539],
        [0.60524556, 0.04514702],
        [0.02445984, 0.01117656],
        [0.22404496, 0.73789853]],

       [[0.60925527, 0.98607238],
        [0.57808405, 0.81475352],
        [0.37632224, 0.35326322],
        [0.77012373, 0.73267687],
        [0.88309952, 0.24618306]],

       [[0.27515928, 0.88661553],
        [0.74748974, 0.76906693],
        [0.50216725, 0.53703779],
        [0.6889586 , 0.42437788],
        [0.91442437, 0.40312663]]])

In [ ]:
np.random.randint((1,2))

array([0, 0])

In [ ]:
def gen_numb():
  a = np.random.rand()
  return a

In [ ]:
gen_numb()

0.4978546239706325

In [ ]:
def gen_numb4():
  a = np.random.randint(4,6)
  return a

In [ ]:
gen_numb4()

5

In [ ]:
import numpy as np
def get_matrix():
    q = int(input())
    w = int(input())
    a=np.ones((q,w))
    print(a)

In [ ]:
get_matrix()

5
6
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
56

56

In [ ]:
i=input("Enter Shape")
li=i.split("x")
lenli=len(li)
x=list(map(int,li))
l1=[]
for i in range(x[lenli-1]):
    l1.append(i)
l2=[]
for i in range(x[lenli-2]):
    l2.append(l1)
l3=[]
for i in range(x[lenli-3]):
    l3.append(l2)
l4=[]
for i in range(x[lenli-4]):
    l4.append(l3)
a=np.array(l4)
print(a)

Enter Shape4x4x4x4
[[[[0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]]

  [[0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]]

  [[0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]]

  [[0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]]]


 [[[0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]]

  [[0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]]

  [[0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]]

  [[0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]]]


 [[[0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]]

  [[0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]]

  [[0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]]

  [[0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]]]


 [[[0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]]

  [[0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]]

  [[0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]]

  [[0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]
   [0 1 2 3]]]]
